### ISSUE TITLE
install fails on w/Node v5.3.0

### ISSUE THREAD

**Issue by DavidDAllen** [flyover/node-box2d#1]
I get this error:
c:\users\d.node-gyp\5.3.0\include\node\node_internals.h(5): fatal error C1083: Cannot open include file: 'util.h': No such file or directory (..\node-box2d.cc) [c:\data\Git\r\node_modules\@flyover\node-box2d\build\libnode-box2d-win.vcxproj]

I've attached the npm debug log file.

[npm-debug.txt](https://github.com/flyover/node-box2d/files/79143/npm-debug.txt)

**Comment by flyover** [comment]
I've republished the module.  Try it now.

**Comment by DavidDAllen** [comment]
Appears to work now. Thanks!
